### ISSUE TITLE
05.11.16

### ISSUE THREAD

**Issue by simplydesigner** [TAHK6e3TOPMO3OB/shared_ptr#1]
- [x] [1](https://github.com/TAHK6e3TOPMO3OB/shared_ptr/blob/eff8b8b51d2d57aabcc4d4a82db7eebcad75538a/include/shared_ptr.cpp#L35)
- [x] [через swap](https://github.com/TAHK6e3TOPMO3OB/shared_ptr/blob/eff8b8b51d2d57aabcc4d4a82db7eebcad75538a/include/shared_ptr.cpp#L55)
- [x] [3](https://github.com/TAHK6e3TOPMO3OB/shared_ptr/blob/eff8b8b51d2d57aabcc4d4a82db7eebcad75538a/include/shared_ptr.cpp#L83)
- [x] [добавьте проверку](https://github.com/TAHK6e3TOPMO3OB/shared_ptr/blob/eff8b8b51d2d57aabcc4d4a82db7eebcad75538a/include/shared_ptr.cpp#L97)

**Comment by TAHK6e3TOPMO3OB** [comment]
https://github.com/TAHK6e3TOPMO3OB/shared_ptr/commit/a7e4ab3d88f4cdeffb37902767699e4ab529db67

**Comment by TAHK6e3TOPMO3OB** [comment]
добавил еще исправлений. смотрите, пожалуйста, последнюю версию.
